---
title: "predicting cities together"
author: "gabriel"
date: "19/8/2019"
output: html_document
---

## loading packages and data

```{r, warning=F, message=F}
pacman:: p_load(readr, h2o, dplyr,ggplot2, caret, imputTS, randomForest, data.table, lubridate, corrplot, quantreg, iClick, h2o)

features_tr <- read_csv("./input/dengue_features_train.csv", 
    col_types = cols(week_start_date = col_date(format = "%Y-%m-%d")))

labels_tr <- read_csv("./input/dengue_labels_train.csv")

features_te <- read_csv("./input/dengue_features_test.csv", 
    col_types = cols(week_start_date = col_date(format = "%Y-%m-%d")))

submission_format <- read_csv("./input/submission_format.csv")


options(scipen=999)



```

create two dataset, train and test

```{r, warning=F}

train <- left_join(x = features_tr, y = labels_tr, by = c("year", "weekofyear", "city"))

test <- left_join(x = features_te, y = submission_format, by = c("year", "weekofyear", "city"))

train$type <- "train"

test$type <- "test"

all <- rbind(train, test)

all %>% group_by(city,year, week_start_date) %>%  mutate(avg_temp = mean(reanalysis_avg_temp_k, reanalysis_air_temp_k, na.rm = T, trim = 0), avg_precip = mean(station_precip_mm, precipitation_amt_mm, na.rm = T, trim = 0),  station_avg_temp_c = NULL, reanalysis_avg_temp_k = NULL, reanalysis_air_temp_k = NULL, station_precip_mm = NULL, precipitation_amt_mm = NULL) # Create avg of tempearature and preciptation


```




```{r, warning=F}

train$type <- "train"

test$type <- "test"

all <- rbind(train, test)
```


The missing values will be replaced by a forecast

```{r}

all <- cbind(all[ , c("city", "type", "week_start_date")] ,  apply(X = all[, which(sapply(all,is.numeric))], MARGIN = 2, function(x) imputeTS::na.kalman(x)))


```


Take the log of total cases

```{r}

all$total_cases <- base::log(all$total_cases)

```


# Modelling 


```{r, warning=F}


all$weekofyear <- as.character(all$weekofyear) 

```

train model to predict Test (All train)

```{r, warning=F, message=F, echo=T}


# Get the best mtry train a random forest using that mtry

all$year <- as.character(all$year)


#all$type <- NULL


```

```{r}

#h2o.init()

#data to h2o cluster

train <- filter(all, type == "train")

train.h2o <- as.h2o(train)

x.indep <- which(names(train.h2o) != "total_cases")

y.dep <- which(names(train.h2o) == "total_cases")  

deep_learn <- h2o.randomForest(y=y.dep, x=x.indep, training_frame = train.h2o)

h2o.performance(deep_learn)




```


### Make final prediction  (test)

```{r, warning=F}

te <- all %>% filter(type == "test")

te$year <- as.character(te$year)


```

The missing values will be replaced by a forecast

```{r, warning=F}

#te <- cbind(te[ , c("city","weekofyear", "type", "week_start_date","year")] ,  apply(X = te[, which(sapply(te,is.numeric))], MARGIN = 2, function(x) imputeTS::na.kalman(x)))

```

### Apply parameters and predict

```{r, warning=F}


test.h2o <- as.h2o(te)

predict.deep_learn <- as.data.frame(h2o.predict(deep_learn, test.h2o))

te$total_cases <- predict.deep_learn$predict

hist(te$total_cases, breaks = c(1000))

#max(te$total_cases)

```


# Final Submission using RF

```{r, warning=F}


submission_format$total_cases <- 10

submission_format$year <- as.character(submission_format$year)

submission_format$weekofyear <- as.character(submission_format$weekofyear)

submission_rf <- full_join(x = submission_format, y = te, by = c("year","weekofyear", "city"))

data.table::setnames(submission_rf, old = "total_cases.y", "total_cases")

submission_rf$total_cases <- exp(submission_rf$total_cases)

submission_rf$total_cases <- base::round(submission_rf$total_cases,0) # Round


submission_rf$total_cases[submission_rf$total_cases < 0 ] <- 0

#base::which(submission_rf$total_cases < 0) <- 0
#if negative, change to 0
```


```{r}

ggplot(sj, aes(week_start_date, y = total_cases)) + geom_line()
ggplot(iq, aes(week_start_date, y = total_cases)) + geom_line()

ggplot(submission_rf, aes(week_start_date, total_cases)) + geom_line() + facet_wrap(city~.)

submission_rf <- submission_rf %>% select(city, year, weekofyear, total_cases) 

write.csv(submission_rf, "submission_rf.csv", quote = F, row.names = F)

summary(submission_format)

summary(submission_rf)


```